---
- name: "FASE 5 | Configurar VRRP Keepalived Balanceado en SWCORELIM2"
  hosts: swcorelim2
  gather_facts: false
  become: true
  connection: local

  vars:
    ansible_connection: local
    ansible_host: 127.0.0.1
    ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - "../host_vars/swcorelim2.yml"

  roles:
    - core_vrrp_keepalived_fase5
