---
fase10f_enabled: true

fase10f_zabbix_url: "http://127.0.0.1/zabbix/api_jsonrpc.php"
fase10f_zabbix_web_url: "http://mon-zabbix-lima.jhalex.local/zabbix"
fase10f_zabbix_user: "Admin"
fase10f_zabbix_password: "zabbix"

fase10f_site_name: "JHALEX Lima"
fase10f_dashboard_name: "JHALEX Lima - Vista Ejecutiva"
fase10f_map_name: "JHALEX Lima - Mapa de Red"

fase10f_host_groups:
  - "JHALEX/LIMA/CORE"
  - "JHALEX/LIMA/GATEWAYS"
  - "JHALEX/LIMA/SERVIDORES"
  - "JHALEX/LIMA/CLIENTES"
  - "JHALEX/LIMA/MONITOREO"

fase10f_hosts:
  - name: "MON-ZABBIX-LIMA"
    ip: "192.168.70.2"
    group: "JHALEX/LIMA/MONITOREO"
    role: "monitoring"
    vlan: "70"
    template_type: "linux"

  - name: "LIM-DC01"
    ip: "192.168.40.10"
    group: "JHALEX/LIMA/SERVIDORES"
    role: "ad_dns_dhcp"
    vlan: "40"
    template_type: "windows"

  - name: "DOC-FILE-BACKUP-LIMA"
    ip: "192.168.80.2"
    group: "JHALEX/LIMA/SERVIDORES"
    role: "file_backup"
    vlan: "80"
    template_type: "linux"

  - name: "ADMIN-LIMA"
    ip: "192.168.10.20"
    group: "JHALEX/LIMA/CLIENTES"
    role: "admin_client"
    vlan: "10"
    template_type: "windows"

  - name: "CLIENT-LIMA"
    ip: "192.168.20.20"
    group: "JHALEX/LIMA/CLIENTES"
    role: "linux_client"
    vlan: "20"
    template_type: "linux"

  - name: "SWCORELIM1"
    ip: "192.168.99.11"
    group: "JHALEX/LIMA/CORE"
    role: "core_primary"
    vlan: "99"
    template_type: "icmp"

  - name: "SWCORELIM2"
    ip: "192.168.99.12"
    group: "JHALEX/LIMA/CORE"
    role: "core_secondary"
    vlan: "99"
    template_type: "icmp"

  - name: "GW VLAN10 Administracion Lima"
    ip: "192.168.10.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "10"
    template_type: "icmp"

  - name: "GW VLAN20 Usuarios Lima"
    ip: "192.168.20.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "20"
    template_type: "icmp"

  - name: "GW VLAN30 Invitados Lima"
    ip: "192.168.30.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "30"
    template_type: "icmp"

  - name: "GW VLAN40 Servidores Lima"
    ip: "192.168.40.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "40"
    template_type: "icmp"

  - name: "GW VLAN50 DMZ Lima"
    ip: "192.168.50.17"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "50"
    template_type: "icmp"

  - name: "GW VLAN60 Voz Lima"
    ip: "192.168.60.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "60"
    template_type: "icmp"

  - name: "GW VLAN70 Monitoreo Lima"
    ip: "192.168.70.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "70"
    template_type: "icmp"

  - name: "GW VLAN80 Backup Lima"
    ip: "192.168.80.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "80"
    template_type: "icmp"

  - name: "GW VLAN99 Gestion Lima"
    ip: "192.168.99.1"
    group: "JHALEX/LIMA/GATEWAYS"
    role: "gateway"
    vlan: "99"
    template_type: "icmp"
